//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ahorros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ahorros()
        {
            this.AhorroTransacciones = new HashSet<AhorroTransacciones>();
        }
    
        public int ahorroId { get; set; }
        public int usuarioId { get; set; }
        public int tipoAhorroId { get; set; }
        public decimal montoInicial { get; set; }
        public decimal montoActual { get; set; }
        public Nullable<System.DateTime> fechaInicio { get; set; }
        public Nullable<int> plazo { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fechaFin { get; set; }
    
        public virtual CatalogoTipoAhorro CatalogoTipoAhorro { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AhorroTransacciones> AhorroTransacciones { get; set; }
    }
}
