//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aportes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aportes()
        {
            this.AportesTransacciones = new HashSet<AportesTransacciones>();
        }
    
        public int aporteId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string tipoAporte { get; set; }
        public decimal monto { get; set; }
        public Nullable<System.DateTime> fechaRegistro { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AportesTransacciones> AportesTransacciones { get; set; }
    }
}
