//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class BeneficiosServiciosCuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BeneficiosServiciosCuenta()
        {
            this.BeneficiosTransacciones = new HashSet<BeneficiosTransacciones>();
        }
    
        public int cuentaBeneficiosServiciosId { get; set; }
        public int usuarioId { get; set; }
        public int beneficioId { get; set; }
        public decimal montoTotal { get; set; }
        public decimal montoPendiente { get; set; }
        public string numeroProforma { get; set; }
        public Nullable<int> plazo { get; set; }
        public Nullable<System.DateTime> fechaCreacion { get; set; }
        public string estado { get; set; }
    
        public virtual BeneficiosServicios BeneficiosServicios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiosTransacciones> BeneficiosTransacciones { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
