//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiarios
    {
        public int beneficiarioId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string nombreCompleto { get; set; }
        public string relacion { get; set; }
        public decimal porcentajeBeneficio { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
