//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ASECCC_DIGITALEntities : DbContext
    {
        public ASECCC_DIGITALEntities()
            : base("name=ASECCC_DIGITALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ahorros> Ahorros { get; set; }
        public virtual DbSet<AhorroTransacciones> AhorroTransacciones { get; set; }
        public virtual DbSet<Aportes> Aportes { get; set; }
        public virtual DbSet<AportesTransacciones> AportesTransacciones { get; set; }
        public virtual DbSet<Beneficiarios> Beneficiarios { get; set; }
        public virtual DbSet<BeneficiosServicios> BeneficiosServicios { get; set; }
        public virtual DbSet<BeneficiosServiciosCuenta> BeneficiosServiciosCuenta { get; set; }
        public virtual DbSet<BeneficiosTransacciones> BeneficiosTransacciones { get; set; }
        public virtual DbSet<CatalogoTipoAhorro> CatalogoTipoAhorro { get; set; }
        public virtual DbSet<CatalogoTipoTransaccion> CatalogoTipoTransaccion { get; set; }
        public virtual DbSet<Notificaciones> Notificaciones { get; set; }
        public virtual DbSet<Prestamos> Prestamos { get; set; }
        public virtual DbSet<PrestamosTransacciones> PrestamosTransacciones { get; set; }
        public virtual DbSet<SeguridadAuditoria> SeguridadAuditoria { get; set; }
        public virtual DbSet<SolicitudesPrestamo> SolicitudesPrestamo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
