//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrestamosTransacciones
    {
        public int transaccionPrestamoId { get; set; }
        public Nullable<int> prestamoId { get; set; }
        public decimal montoAbonado { get; set; }
        public Nullable<System.DateTime> fechaPago { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
