//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamos()
        {
            this.PrestamosTransacciones = new HashSet<PrestamosTransacciones>();
        }
    
        public int prestamoId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<decimal> montoAprobado { get; set; }
        public int plazo { get; set; }
        public Nullable<decimal> cuotaSemanal { get; set; }
        public string tipoPrestamo { get; set; }
        public string estadoPrestamo { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEstado { get; set; }
        public Nullable<decimal> saldoPendiente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PrestamosTransacciones> PrestamosTransacciones { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
