//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguridadAuditoria
    {
        public int auditoriaId { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public string accion { get; set; }
        public Nullable<System.DateTime> fechaAccion { get; set; }
        public string direccionIp { get; set; }
        public string tipoAccion { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
