//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesPrestamo
    {
        public int solicitudPrestamoId { get; set; }
        public int usuarioId { get; set; }
        public string estadoCivil { get; set; }
        public bool pagaAlquiler { get; set; }
        public Nullable<decimal> montoAlquiler { get; set; }
        public string nombreAcreedor { get; set; }
        public Nullable<decimal> totalCredito { get; set; }
        public Nullable<decimal> abonoSemanal { get; set; }
        public Nullable<decimal> saldoCredito { get; set; }
        public string nombreDeudor { get; set; }
        public Nullable<decimal> totalPrestamo { get; set; }
        public Nullable<decimal> saldoPrestamo { get; set; }
        public string tipoPrestamo { get; set; }
        public decimal montoSolicitud { get; set; }
        public string estadoSolicitud { get; set; }
        public decimal cuotaSemanalSolicitud { get; set; }
        public int plazoMeses { get; set; }
        public string propositoPrestamo { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
