//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASECCC_Digital.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.Ahorros = new HashSet<Ahorros>();
            this.Aportes = new HashSet<Aportes>();
            this.Beneficiarios = new HashSet<Beneficiarios>();
            this.BeneficiosServiciosCuenta = new HashSet<BeneficiosServiciosCuenta>();
            this.Notificaciones = new HashSet<Notificaciones>();
            this.Prestamos = new HashSet<Prestamos>();
            this.SeguridadAuditoria = new HashSet<SeguridadAuditoria>();
            this.SolicitudesPrestamo = new HashSet<SolicitudesPrestamo>();
        }
    
        public int usuarioId { get; set; }
        public string nombreCompleto { get; set; }
        public string correoElectronico { get; set; }
        public string contrasena { get; set; }
        public string tipoIdentificacion { get; set; }
        public string identificacion { get; set; }
        public System.DateTime fechaNacimiento { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string rol { get; set; }
        public string estadoAfiliacion { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public string resetToken { get; set; }
        public Nullable<System.DateTime> resetTokenExpiry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ahorros> Ahorros { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Aportes> Aportes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiarios> Beneficiarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BeneficiosServiciosCuenta> BeneficiosServiciosCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notificaciones> Notificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prestamos> Prestamos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguridadAuditoria> SeguridadAuditoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesPrestamo> SolicitudesPrestamo { get; set; }
    }
}
